apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-moles
  labels:
    run: test-moles
spec:
  replicas: 6
  selector:
    matchLabels:
      run: test-moles
  template:
    metadata:
      labels:
        run: test-moles
    spec:
      containers:
      - image: whack-a-mole/moles
        resources:
          requests:
            cpu: "0.05"
            memory: "64Mi"
          limits:
            memory: "128Mi"
            cpu: "0.1"
        name: test-moles
        ports:
        - containerPort: 8080
