apiVersion: v1
kind: Service
metadata:
  name: whack-a-mole-backend
  labels:
    app: whack-a-mole-backend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: whack-a-mole-backend
  selector:
    app: whack-a-mole-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whack-a-mole-backend
  labels:
    run: whack-a-mole-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whack-a-mole-backend
      tier: web
  template:
    metadata:
      labels:
        app: whack-a-mole-backend
        tier: web
    spec:
      containers:
      - image: whack-a-mole/backend
        resources:
          requests:
            cpu: "0.05"
            memory: "64Mi"
          limits:
            memory: "128Mi"
            cpu: "0.1"
        name: whack-a-mole-backend
        ports:
        - containerPort: 8081